language: python
sudo: false

env:
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="lua=5.4"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - make install_dev

script:
  - make test

notifications:
  email:
    on_success: change
    on_failure: always
